### ISSUE TITLE
Do we need a new name?

### ISSUE THREAD

**Issue by ftrotter** [ftrotter/OSE#2]
Monty has an identical concept called "Business Source".

My name is good because its clear how it works, and references Open Source

His name is good because it emphasises the whole reason that the license exists which is to make viable businesses.

I think a name change is in order that does both. Of course we get a fun acroymn, if we merge the names this way:

Business
Open 
Source
Someday 

If someone else has a name that they would be willing to contribute (entirely) to this project.. please list it below... otherwise we will go with BOSS.

-FT

**Comment by indolering** [comment]
I think "eventually" and "someday" is really poor framing.  Furthermore, what if you are going from a strong copyleft to a weak copy left license?  Say AGPLv3 to Apache or from a Creative Commons non-commercial ([BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode)) to [CC0](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) (public domain)?

I think framing it as an evolution, metamorphosis, or incubation would be much better.  Besides, Open Source Evolution wouldn't require changing your acronym!

**Comment by ftrotter** [comment]
Thanks for the discussion, changing status to closed.
